name: Feature request
description: Suggest an improvement
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem should this solve?
      description: Explain the use case, not only the proposed implementation.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
